
/*
 * This source file was generated by the Gradle 'init' task
 */
package descargar.musica;

import java.io.File;

import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) throws Exception {

        String homeUsuario = System.getProperty("user.home");
        String rutaDescargas = homeUsuario + File.separator + "Downloads";

        Config config = new Config(rutaDescargas, "mp3");
        Descargador descargar = new Descargador(config);

        String cancionElegida = JOptionPane.showInputDialog(null, "Link De la cancion:", "Preparando Todo",
                JOptionPane.QUESTION_MESSAGE);
        descargar.descargarCancion(cancionElegida);
    }

}
